### ISSUE TITLE
invalid license

### ISSUE THREAD

**Issue by RandLily** [colabar/nopfire#2]
![image](https://github.com/colabar/nopfire/assets/48348945/f651fc4d-dde3-4247-a2d2-45bc21d597ca)
after choose "Get a new free license"，i get nothing print......

**Comment by colabar** [comment]
Thanks for reporting this issue.
Bug confirmed. 
Please try [nopfire v0.0.4](https://github.com/colabar/nopfire/releases/tag/v0.0.4)
